/** Re-export from mainframe/shared (single source for server + browser). */
export { DEFAULT_FRAME_WIDTH, DEFAULT_FRAME_HEIGHT, DEFAULT_SCALE_MODE, PLAYBACK_MODES, DEFAULT_PLAYBACK, TRIGGER_TYPES, DEFAULT_TRIGGER_TYPE, DEFAULT_FRAME_RATE, MAX_FRAMES_PER_ROW, VALID_BIT_DEPTHS, SYNC_MODES, DEFAULT_SYNC_MODE, SYNC_LENGTH_PRESETS, DEFAULT_BEATS_PER_BAR } from '../../shared/clipSchema.js';
